package stytch

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/stytchauth/stytch-go/v16/stytch/b2b/b2bstytchapi"
)

// Client is a thin wrapper around the autogenerated Stytch B2B API client.
type Client struct {
	api    *b2bstytchapi.API
	config Config
}

// NewClient constructs the shared Stytch API client using the supplied configuration.
func NewClient(cfg Config) (*Client, error) {
	httpClient := &http.Client{
		Timeout: cfg.APITimeout,
	}

	var opts []b2bstytchapi.Option
	opts = append(opts, b2bstytchapi.WithHTTPClient(httpClient))

	baseURI := strings.TrimSuffix(cfg.BaseURL, "/")
	if baseURI != "" {
		opts = append(opts, b2bstytchapi.WithBaseURI(baseURI))
	}

	apiClient, err := b2bstytchapi.NewClient(cfg.ProjectID, cfg.Secret, opts...)
	if err != nil {
		return nil, fmt.Errorf("create stytch client: %w", err)
	}

	return &Client{
		api:    apiClient,
		config: cfg,
	}, nil
}

// API exposes the underlying autogenerated API for advanced use-cases.
func (c *Client) API() *b2bstytchapi.API {
	return c.api
}

// Config returns the hydrated configuration.
func (c *Client) Config() Config {
	return c.config
}
